# Generated by Django 2.2.9 on 2023-02-20 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20230220_1051'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostForm',
        ),
    ]
